# This file describes an application. You can have multiple applications
# in the same project.
# sampled from https://github.com/magento/magento-cloud/blob/master/.magento.app.yaml

# The name of this app. Must be unique within a project.
name: ddpmodule

# The toolstack used to build the application.
type: php:7.4
build:
    flavor: composer

# Enable extensions required by Magento 2
runtime:
    extensions:


# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the environment variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"


# The configuration of app when it is exposed to the web.
web:


# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:


hooks:

# Default Magento 2 cron jobs
crons:


# Environment variables
variables:
    env:
